version: '3.8'

services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"  # JupyterLab
    volumes:
      - ./data/dags:/app/dags  # Direktori data JupyterLab di host
      - ./data/envs:/app/envs  # Direktori environment Conda di host
      - ./config:/root/.jupyter  # Direktori konfigurasi JupyterLab di host
    environment:
      - TZ=Asia/Jakarta  # Set zona waktu Jakarta
    command: bash -c "source activate myenv && jupyter lab --NotebookApp.token=Exim2024!! --ip=0.0.0.0 --no-browser --allow-root"

  airflow-webserver:
    build: .
    ports:
      - "8080:8080"  # Airflow webserver
    volumes:
      - ./data/dags:/app/airflow/dags  # Direktori DAGs di host
      - ./data/envs:/app/envs  # Direktori environment Conda di host
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+pymysql://airflow:airflow@mysql/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Set LocalExecutor sebagai executor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False  # Nonaktifkan contoh DAGs
      - TZ=Asia/Jakarta  # Set zona waktu Jakarta
    depends_on:
      - mysql
    command: bash -c "source activate myenv && airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver --host 0.0.0.0 --port 8080"

  airflow-scheduler:
    build: .
    volumes:
      - ./data/dags:/app/airflow/dags  # Direktori DAGs di host
      - ./data/envs:/app/envs  # Direktori environment Conda di host
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+pymysql://airflow:airflow@mysql/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Set LocalExecutor sebagai executor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False  # Nonaktifkan contoh DAGs
      - TZ=Asia/Jakarta  # Set zona waktu Jakarta
    depends_on:
      - mysql
    command: bash -c "source activate myenv && airflow scheduler"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
    volumes:
      - ./data/mysql:/var/lib/mysql  # Direktori data MySQL di host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"  # Port untuk phpMyAdmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=airflow
      - PMA_PASSWORD=airflow
    depends_on:
      - mysql

# Tidak perlu mendefinisikan volume di sini jika hanya menggunakan volume yang di-mount dari direktori host
